export default {

  GET_POPULAR_MOVIES:           'GET_POPULAR_MOVIES',
  GET_POPULAR_MOVIES_SUCCESS:   'GET_POPULAR_MOVIES_SUCCESS',
  GET_POPULAR_MOVIES_FAILED:    'GET_POPULAR_MOVIES_FAILED',

  GET_TOP_RATED_MOVIES:         'GET_TOP_RATED_MOVIES',
  GET_TOP_RATED_MOVIES_SUCCESS: 'GET_TOP_RATED_MOVIES_SUCCESS',
  GET_TOP_RATED_MOVIES_FAILED:  'GET_TOP_RATED_MOVIES_FAILED',

  GET_UPCOMING_MOVIES:         'GET_UPCOMING_MOVIES',
  GET_UPCOMING_MOVIES_SUCCESS: 'GET_UPCOMING_MOVIES_SUCCESS',
  GET_UPCOMING_MOVIES_FAILED:  'GET_UPCOMING_MOVIES_FAILED',

  GET_BANNER_TRENDING:          'GET_BANNER_TRENDING',
  GET_BANNER_TRENDING_SUCCESS:  'GET_BANNER_TRENDING_SUCCESS',
  GET_BANNER_TRENDING_FAILED:   'GET_BANNER_TRENDING_FAILED',

  GET_LIST_GENRES:              'GET_LIST_GENRES',
  GET_LIST_GENRES_SUCCESS:      'GET_LIST_GENRES_SUCCESS',
  GET_LIST_GENRES_FAILED:       'GET_LIST_GENRES_FAILED',

}